project_id = "nfl-conquest"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[auth]
enabled = true
enable_anonymous_sign_ins = false

[realtime]
enabled = true
